apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - name: usuarios
        image: usuariosmicroservice.azurecr.io/amiltonr/usuariomicroservice
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: usuario-microservice-svc
spec:
  selector:
    app: usuarios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
